# Generated by Django 3.0.8 on 2020-08-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20200804_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientlist',
            name='ingredient_list_title',
            field=models.CharField(default='Zutaten', max_length=100),
        ),
    ]
