# Generated by Django 3.0.8 on 2020-08-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.FloatField(default=1),
        ),
    ]
